# Generated by Django 5.1.2 on 2024-12-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='cena',
            field=models.CharField(default=0, max_length=256),
        ),
    ]
